apiVersion: storage.platform.urukube.io/v1alpha1
kind: US3Bucket
metadata:
  name: urukube-test-bucket-472506473117
  namespace: default
spec:
  parameters:
    awsAccountId: "472506473117"
    region: us-east-1
    versioning: false
    buId: BU001
